(executable
 (name test_migration)
 (modules test_migration test_support)
 (libraries alcotest sqlite3 kcal))

(executable
 (name test_domain)
 (modules test_domain)
 (libraries alcotest kcal))

(executable
 (name test_meal_store)
 (modules test_meal_store test_support)
 (libraries alcotest sqlite3 kcal))

(executable
 (name test_weigh_in_store)
 (modules test_weigh_in_store test_support)
 (libraries alcotest sqlite3 kcal))

(executable
 (name test_auth)
 (modules test_auth test_support)
 (libraries alcotest sqlite3 kcal))

(executable
 (name test_service_isolation)
 (modules test_service_isolation test_support)
 (libraries alcotest sqlite3 kcal))
